- name: Trustification
  hosts: trustification
  vars:
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-trustification-service-rhel9:04e98ed6ad5cae7d77ab709abeaf15da66731d69 # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
