- name: Trustification
  hosts: trustification
  vars:
    tpa_single_node_trustification_image: registry.redhat.io/rhtpa/rhtpa-rhel10:3d2a2ee7c1e69746ef35f085e04f4157e769d6b8 # noqa yaml[line-length]
  vars_files:
    - vars/main.yml
  tasks:
    - name: Include TPA single node
      ansible.builtin.include_role:
        name: tpa_single_node
