---
- name: Create configmap to create database
  ansible.builtin.template:
    src: "{{ role_path }}/templates/manifests/init/create_database/Configmap.yaml.j2"
    dest: "{{ tpa_single_node_kube_manifest_dir }}/ConfigMaps/create_database.yaml"
    mode: "0600"
  register: configmap_create_db

- name: Set configmaps to create database
  ansible.builtin.set_fact:
    create_db_configmaps: >-
      {{
        [
          tpa_single_node_kube_manifest_dir + '/ConfigMaps/create_database.yaml'
        ]
      }}

- name: Create database
  ansible.builtin.include_tasks: install_manifest.yml
  vars:
    podman_spec:
      state: started
      systemd_file: create-db
      network: "{{ tpa_single_node_podman_network }}"
      kube_file_content: "{{ lookup('ansible.builtin.template', 'manifests/init/create_database/Deployment.yaml.j2') | from_yaml }}"
      configmaps: "{{ create_db_configmaps }}"
